name: IGNpcUtils
version: '${project.version}'
main: me.icegames.ignpcutils.IGNpcUtils
api-version: 1.8.8
author: IceGames
depend: [Citizens]
commands:
  npcutils:
    description: Comandos do IGNpcUtils
    usage: /npcutils <subcomando>
    permission: npcutils.admin
permissions:
  npcutils.admin:
    description: Permissao para usar comandos do IGNpcUtils
    default: op
